name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v7
      with:
        dotnet-version: 6.0.101

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Run Unit Tests
      run: dotnet test Tests/Tests.csproj --no-restore --no-build --configuration Release --logger:"trx;LogFileName=test_results.trx"

    - name: Publish Test Results
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: TestResults

  integration_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v7
      with:
        dotnet-version: 6.0.101

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Run Integration Tests
      run: dotnet test IntegrationTests/IntegrationTests.csproj --no-restore --no-build --configuration Release --logger:"trx;LogFileName=integration_test_results.trx"

    - name: Publish Integration Test Results
      uses: actions/upload-artifact@v2
      with:
        name: Integration Test Results
        path: IntegrationTestResults
